### ISSUE TITLE
NIST help pages

### ISSUE THREAD

**Issue by hoodriverheather** [Labcas-NIST/Labcas-ui#19]
Create and update the help documentation for for NIST LabCAS.

## Todo

- [ ] Create upload documentation. Include how to add to an existing collection "incremental uploads"
- [ ]  update and include core metadata and upload templates for both Genome Editing and Flow Cytometry
- [ ]  Review download doc and update with NIST as appropriate
