### ISSUE TITLE
Update NIST KSDB

### ISSUE THREAD

**Issue by hoodriverheather** [Labcas-NIST/Labcas-ui#25]
Update KSDB to accommodate NIST structure

## Todo

- [ ] Review NIST use cases to create/update google doc of possible updated KSDB model https://docs.google.com/document/d/1MuX2agvvOmdZRv_oao-wPAhQmEWPX0g5yclw8pd6UNU/edit
- [ ] Generate slides to review these updates with NIST on a bi-weekly call
- [ ] Look into complexity of including NIST core metadata in KSDB
